
services:
  gateway-api:
    image: registry.cn-shenzhen.aliyuncs.com/tokengo/gateway-api
    restart: always
    container_name: gateway-api
    build:
      context: ./src
      dockerfile: Gateway/Dockerfile
    ports:
      - 8200:8080
    networks:
      - token
    volumes:
      - ./Gateway.db:/app/Gateway.db

  gateway-web:
    image: registry.cn-shenzhen.aliyuncs.com/tokengo/gateway-web
    restart: always
    container_name: gateway-web
    build:
      context: ./web
      dockerfile: Dockerfile
    privileged: true
    environment:
      api_url: http://token-ai.cn:8200
    ports:
      - 10800:80
    networks:
      - token


networks:
  token:
    driver: bridge