global using FastGateway.EFCore;
global using Mapster;
global using Microsoft.EntityFrameworkCore;
global using FastGateway.Domain;
global using FastGateway.Dto;
global using System.Text.Json;
global using FastGateway.Core;
global using FastGateway.Services;
global using Microsoft.AspNetCore.StaticFiles;