name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 登录Docker Hub
      run: docker login -u aidotnet -p ${{ secrets.DOCKER }} 
    - uses: actions/checkout@v4
    - name: 构建镜像
      run: docker build . --file src/FastGateway.Service/Dockerfile --tag aidotnet/fast-gateway:latest
    - uses: actions/checkout@v4
    - name: 推送镜像
      run: docker push aidotnet/fast-gateway:latest
